### ISSUE TITLE
 write /tmp/go-link-314280739/go.o: cannot allocate memory

### ISSUE THREAD

**Issue by mfojtik** [openshift/test-infra#155]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20019/pull-ci-origin-verify/845/

It looks like the pods that run the verify task should get more memory? 

/cc @smarterclayton 
/cc @stevekuznetsov

**Comment by smarterclayton** [comment]
Yeah, open a PR to openshift/release to change ci-operator/config/openshift/origin/master.json that increases the limit and request for verify by a few GB.
