### ISSUE TITLE
test_pull_request_origin_cmd fails because of too many open files

### ISSUE THREAD

**Issue by mfojtik** [openshift/test-infra#158]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20362/test_pull_request_origin_cmd/15993/

```
FATAL: command execution failed
java.io.IOException: error=24, Too many open files
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "/bin/bash" (in directory "/var/lib/jenkins/jobs/test_pull_request_origin_cmd/workspace"): error=24, Too many open files
```

Might be random glitch.

/cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@dobbymoodge looks like we are having issues on ci.openshift?

**Comment by stevekuznetsov** [comment]
@dobbymoodge can you please close this out or post a resolution

**Comment by dobbymoodge** [comment]
@stevekuznetsov The limits changes are in place in `/etc/security/limits.d/30-nofiles.conf`, but I need to restart Jenkins for them to take effect. Do we have a document describing how to rekick tests after restarting Jenkins?

**Comment by stevekuznetsov** [comment]
oh boy. I'm not sure we have a process for that right now actually

**Comment by stevekuznetsov** [comment]
I guess we could edit the configuration to allow us room to schedule 0 new jobs to jenkins, then restart, then re-edit the config back to normal. @dobbymoodge let's sync tomorrow on that

**Comment by dobbymoodge** [comment]
Jenkins has been rebooted since those changes were added. :D
