### ISSUE TITLE
failed to push cherry-picked changes in GitHub

### ISSUE THREAD

**Issue by jcpowermac** [openshift/test-infra#185]
**What happened**:

```
failed to push cherry-picked changes in GitHub: pushing failed, output: "remote: Not Found\nfatal: repository 'https://openshift-cherrypick-robot:CENSORED@github.com/openshift-cherrypick-robot/openshift/installer/' not found\n", error: exit status 128
```

**What you expected to happen**:
No error

**How to reproduce it (as minimally and precisely as possible)**:

Add comment `/cherrypick release-4.x`

**Please provide links to example occurrences, if any**:
https://github.com/openshift/installer/pull/2749
https://github.com/openshift/cluster-dns-operator/pull/148

**Anything else we need to know?**:

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/15479
