### ISSUE TITLE
Gubernator is pointing to the wrong Jenkins master

### ISSUE THREAD

**Issue by kargakis** [openshift/test-infra#42]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16686/origin-ci-ut-origin/20/ 

We could possibly expose the proxy via a route and use the route in Gubernator.

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
We need to not have GCS issues and never see the 404

**Comment by stevekuznetsov** [comment]
But yes proxy is the way forward here
