### ISSUE TITLE
Gubernator Internal Fatal XML Parse Error

### ISSUE THREAD

**Issue by kargakis** [openshift/test-infra#44]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16615/test_pull_request_origin_extended_conformance_gce/9168/#gubernator-internal-fatal-xml-parse-error

```
not well-formed (invalid token): line 1, column 0
```
@stevekuznetsov

**Comment by kargakis** [comment]
@stevekuznetsov can we enable the bots for this repo? I would suggest setting an organizational hook so we won't need to set them for each repo individually.

**Comment by stevekuznetsov** [comment]
Sure. This bug is from my change to XML gathering, will fix.

**Comment by kargakis** [comment]
@stevekuznetsov is this fixed now?

**Comment by stevekuznetsov** [comment]
Yes, should be fine

/close

**Comment by stevekuznetsov** [comment]
@openshift-ci-robot get out of here
