### ISSUE TITLE
jenkins-config-updater: use github API to get the script instead of git cloning

### ISSUE THREAD

**Issue by kargakis** [openshift/test-infra#65]
[Similar to the upstream config-updater plugin](https://github.com/kubernetes/test-infra/blob/8aaff58561b0753da6b5a44bd916461957564c28/prow/plugins/updateconfig/updateconfig.go#L54).

cc: @stevekuznetsov @paradigm

**Comment by stevekuznetsov** [comment]
@kargakis since we need all the files to actually process and push up... and we wanted to be able to do that for all the different types of updates we were going to do, it felt easier to clone
