### ISSUE TITLE
Wrong number of succeeded tests

### ISSUE THREAD

**Issue by dmage** [openshift/test-infra#76]
We have a new repository and a new jenkins job for unit tests. For some reason Gubernator doesn't doesn't count tests: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/5/test_pull_request_image_registry_unit/1/

**Comment by stevekuznetsov** [comment]
Not seeing any jUnit in the artifacts - where does your job leave them? Can you inspect the GCS upload code in the job?

**Comment by dmage** [comment]
@stevekuznetsov could it be because of `junit_analysis: False` in the job config?

**Comment by stevekuznetsov** [comment]
No, that just stops Jenkins from publishing the jUnit into the job itself -- can you track down where your e2e is putting the jUnit XML?

**Comment by dmage** [comment]
I have no idea where I should look for it.

**Comment by smarterclayton** [comment]
I suspect this is fixed now with the new jobs.
