### ISSUE TITLE
Discourage, warn and audit on manually adding lgtm label

### ISSUE THREAD

**Issue by tnozicka** [openshift/test-infra#80]
Unfortunately people tend to add `lgtm` labels on their own PRs avoiding code reviews and submit queue. We can't really forbid it but SQ should post a comment to make sure everyone on the PR gets notification and to discourage this behaviour. Maybe mention someone who will decide if such use was justifiable or abuse.

/cc @kargakis

**Comment by kargakis** [comment]
Please open this in k8s/test-infra

**Comment by tnozicka** [comment]
I am not aware of this being a problem upstream, that's why I opened it here.

**Comment by kargakis** [comment]
Both the SQ and tide (the new merge pool) are upstream code and we don't plan on patching. Also, the problem you describe is applicable upstream, too (I can add labels manually if I want to).
