### ISSUE TITLE
gubernator: link to github is broken

### ISSUE THREAD

**Issue by kargakis** [openshift/test-infra#94]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_cross/1098/

`Refs | master:d3cdfecb` redirects to [nowhere](https://github.com/None/commit/d3cdfecb089dc67721400a8d7df26b723cd305a9).

/area gubernator
@deads2k @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Upstream has the `None` issue in those links as well

/close
